def label = "pod-${UUID.randomUUID().toString()}"

podTemplate(label: label, containers: [
  containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true),
  containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.8.8', command: 'cat', ttyEnabled: true)
  ],
volumes: [
  hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock')
]) {
  node(label) {
    def project = 'karthikys'
    def app = 'myapp'
    def imageTag = "${project}/${app}:${env.BUILD_NUMBER}" 
  
    // Checkout source and Build FlaskApp Docker Image
    stage('Checkout and Build') {
      git url: 'https://github.com/Karthikys6/k8swebapp.git'
      container('docker') {
        sh """
          cd `pwd`/MyApp
          docker build -t ${imageTag} .
          """
     }
     }
  
     // Deploy to k8s
    stage('Deploy MyApp') {
       git url: 'https://github.com/Karthikys6/k8swebapp.git'
       container('kubectl') {
        sh """
           cd `pwd`/MyApp/k8s
           sed -i.bak 's#${project}/${app}:2#${imageTag}#' myapp_deployment.yaml
           kubectl apply -f myapp_deployment.yaml
           kubectl apply -f myapp_service.yaml
           echo "WebApp is running on `kubectl get svc/myapp -o=jsonpath='{.spec.ports[*].nodePort}'`" 
           """
     }    
     } 
}  
}